{
  "hash": "bae09c820c76e2f2b97380ff835d00a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Workflow Linear Models I\"\nformat:\n  html: \n    toc: true\n    code-fold: show\n    code-summary: \"Show the code\"\n    toc-depth: 3\n    embed-resources: true\n    self-contained-math: true\n  pdf:\n    toc: true\n    toc_depth: 5\nauthors:\n  - name: Chris Howden\n    address: Sydney Informatics Hub, Sydney University\n    email: chris.howden@sydney.edu.au\n  - name: Stanislaus Stadlmann\n    address: Sydney Informatics Hub, Sydney University\n    email: stanislaus.stadlmann@sydney.edu.au\n---\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(171974)\nproject <- \"R Workshop - Linear Models\"\nversion <- \"1\"\ndate <- format(Sys.Date(), \"%d-%m-%Y\")\ntitle <- paste(project, \" v\", version, \" \", date, sep = \"\")\n```\n:::\n\n\nThe title of this project is R Workshop - Linear Models v1 23-05-2024. The slides for the presentation accompanying this workflow can be found [here](https://sydney-informatics-hub.github.io/stats-resources/statistical_modelling.html#linear-models-1-linear-regression-anova-ancova-and-repeated-measures-a-simple-mixed-model).\n\nIn this workflow we focus on practical data analysis by presenting statistical workflows applicable in any software for four of the most common univariate analyses: linear regression, ANOVA, ANCOVA, and repeated measures (a simple mixed model) – all assuming a normal (gaussian) residual. These workflows can be easily extended to more complex models. The R code used to create output is also included.\n\nIn order to re-run this `.qmd` file, either open it with RStudio and press \"render\" or, if you want both the `.pdf` and the `.html` file to be produced, run the following code with this `.qmd` file being present in your working directory: `quarto::quarto_render(\"linear_modelsI_workflow.qmd\", output_format = \"all\")`\n\n## Libraries\n\nBefore we delve into the content, it is necessary to load certain libraries. If you want to use them, please install them beforehand with `install.packages(\"library_name\")`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsuppressPackageStartupMessages({\n  library(\"tibble\")\n  library(\"magrittr\")\n  library(\"ggplot2\")\n  library(\"emmeans\")\n  library(\"lme4\")\n  library(\"lmerTest\")\n  library(\"gglm\")\n  library(\"patchwork\")\n  library(\"writexl\")\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'writexl' was built under R version 4.3.2\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# GGplot theme\ntheme_set(theme_bw())\n\n# No warnings\noptions(warn = -1)\n```\n:::\n\n\n## Simple Linear Models\n\nFor this part, we assume that we have a dataset called `dataset` with two variables:\n\n* `response` which is the response or target variable, i.e. the 'variable of interest'.\n* `predictor1` which is the predictor variable, i.e. the variable that we are using to explain the variance in `response`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npredictor1 <- rnorm(100, 6, 0.25)\nvariance <- rnorm(100, 0, 0.05)\nresponse <- 1 + 0.5 * predictor1 + variance\ndataset <- data.frame(response, predictor1)\n```\n:::\n\n\n### Step 1:  Exploratory Data Analysis\n\nIn this section, we first check for validity of assumptions prior to the formal model fitting procedure using statistical diagnostics.\n\n#### Linearity Assumption\n\nA simple linear model assumes a linear relationship between our predictor(s) and the target variable. In order to verify this, we create a scatterplot between `predictor1` and `response`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = dataset, aes(x = predictor1, y = response)) +\n  geom_point() +\n  labs(x = \"predictor1 values\", y = \"response values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nAs we can see, the `response` values rise nicely with increased values of `predictor1`, indicating a linear relationship. Have a look at a graph, in which linearity is clearly not present:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = rnorm(100), y = 1 + x^2 + rnorm(100, sd = 0.5)) %>%\n  ggplot(data = ., aes(x = x, y = y)) +\n  geom_point() +\n  labs(x = \"predictor1 values\", y = \"response values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nIn this above graph, the response is actually dependent on $x^2$, not $x$.\n\n#### Assumption of Independence\n\nAnother assumption of linear models is that the observations are not dependent on each other. One way to check this is to do a serial plot, which lines up all observations in order of appearance. If any pattern can be detected, they are likely to not be independent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = dataset, aes(\n  x = seq_along(response),\n  y = response\n)) +\n  geom_point() +\n  labs(x = \"index\", y = \"response values\") +\n  ggplot(data = dataset, aes(\n  x = seq_along(response),\n  y = predictor1\n)) +\n  geom_point() +\n  labs(x = \"index\", y = \"predictor.linear1 values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThere are no visible patterns in the above graph. A problematic pattern could occur in time-dependent observations, like below:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ny0 <- 10\ny_1 <- stats::filter(c(y0, runif(99, -0.5, 0.5)), 0.75, method = \"recursive\")\nqplot(seq_along(y_1), y_1, geom = \"point\") +\n  labs(x = \"index values\", y = \"response values\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nIn the graph above, we can clearly see how each observations depend on the ones that came before.\n\n#### Normality Assumption\n\nThe assumption of normality is technically only relevant for residuals, which can only be obtained post-model fit. But it's still a good idea to check normality of the response variable , since they are related.\n\nFirst, we create a histogram of all `response` observations, and have a look at the `predictor1` values as well:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = dataset, aes(x = response, y = after_stat(density))) +\n  geom_histogram(fill = \"cornflowerblue\", bins = 15, col = \"black\") +\n  ggplot(data = dataset, aes(x = predictor1, y = after_stat(density))) +\n  geom_histogram(fill = \"cornflowerblue\", bins = 15, col = \"black\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nWhat we're looking for here is a roughly symmetric distributions with a single peak.\n\n#### Outlier checking\n\nThis is a also very poorly understood assumption. We want a model represent the bulk of the data. We don't want it biased towards 1 or 2 outlying influential points. Just like checking the normality assumption we can only test this for sure once we have fit a model. However, it is always worth looking at all our data to see if there are any outliers we might need to deal with. The best way to do this is via histograms, re-using the one created above.\n\n\n### Step 2: Model fitting\n\nAfter a sucessful Exploratory Data Analysis, we use `lm()` to fit a linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(response ~ predictor1, data = dataset)\n```\n:::\n\n\n### Step 3: Model diagnostics\n\nIn order to gauge the model fit, we first visually display the residuals. Residuals are variability in our response that cannot be explained by the model. Visually, they appear as the distance between the fitted line and the observed datapoints. Have a look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = dataset, aes(x = predictor1, y = response)) +\n  geom_point() +\n  geom_line(data = NULL, aes(x = predictor1, y = fitted(model)), col = \"firebrick\") +\n  labs(x = \"predictor1 values\", y = \"response values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nWe are looking for a few things here: Firstly, that the deviation from the line is roughly equal across the spread of `predictor1`. Secondly, that the residuals are normally distributed. We can also display the deviations from the line in a histogram including a kernel density graph, like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_res <- residuals(model)\nggplot(data = NULL, aes(x = model_res, y = after_stat(density))) +\n  geom_histogram(fill = \"cornflowerblue\", bins = 15, col = \"black\") +\n  labs(x = \"predictor1 values\", y = \"density\") +\n  ggplot(data = NULL, aes(x = model_res, y = after_stat(density))) +\n  geom_density(fill = \"firebrick\") +\n  geom_rug(aes(y = NULL)) +\n  labs(x = \"predictor1 values\", y = \"density\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nUsing a histogram it is often easier to spot irregularities. In this case, using the graph above and below we can confirm that the residuals are normally and equally distributed across the line.\n\nOther diagnostic plots can be produced with `plot(model_object_name)`. The `gglm` package produces the same plots but using the graphing package `ggplot2`, the plots of which look a little more up-to-date:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngglm(model, theme = theme_bw()) +\n  ggplot(data = model) +\n  stat_cooks_obs() +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", col = \"red\") +\n  plot_layout(nrow = 2, heights = c(2, 1))\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe following plots are produced above:\n\n1. Residuals vs Fitted: This plot displays the model residuals vs the fitted values. We are looking to confirm a linear relationships between predictor variables and the outcome variable here.\n2. Normal Q-Q plot: This plot displays empirical normal distribution quantiles versus the theoretical ones. This plot seeks to confirm the normal distribution of residuals, as we did before with the histogram.\n3. Scale-Location: This plot shows whether residuals are equally spread along the range of predictors. A more or less horizontal line is what we're looking for here.\n4. Residuals vs Leverage: In this plot, we're identifying influental observations. If one observation is unreasonably far to the right, it indicates an influental outlier. \n5. Cook's distance plot: This plot shows Cook's distance numbers for each observation. R uses a cutoff of 0.5, so observations above that cut-off could indicate a problem.\n\nAll of these plots look ideal. \n\n### Step 4: Goodness of fit\n\nIn this part, we want to check the goodness-of-fit of the model. Above, we already displayed the fitted values vs the residuals of the model. It also makes sense to compare the values of each predictor (explanatory variable), as well as the response with the residuals, to make sure the linearity assumption holds for each variable that we're predicting with. In our case, we only have one predictor variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 1\nggplot(dataset, aes(x = predictor1, y = residuals(model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\", linetype = \"dashed\") +\n  labs(x = \"predictor1\", y = \"model residuals\", title = \"predictor1 vs. residuals\") +\n# Plot 2\n  ggplot(dataset, aes(x = response, y = residuals(model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\", linetype = \"dashed\") +\n  labs(x = \"response\", y = \"model residuals\", title = \"response vs. residuals\") +\n# Plot 3\n  ggplot(dataset, aes(x = predict(model), y = residuals(model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\", linetype = \"dashed\") +\n  labs(x = \"fitted values\", y = \"model residuals\", title = \"fitted values vs residuals\") +\n  plot_layout(ncol = 2)\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nAs we can see, the linearity assumption holds nicely. Let's also check the response vs predicted plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dataset, aes(x = response, y = predict(model))) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, col = \"red\") +\n  labs(y = \"predicted\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThis plot is a good visual representation of model fit. If the response is being exactly predicted than we expect it to fall along the 1:1 line.\n\nNow, we look at the summary output of our linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = response ~ predictor1, data = dataset)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.115978 -0.030085 -0.001874  0.028932  0.161342 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.94554    0.11584   8.162 1.14e-12 ***\npredictor1   0.50825    0.01927  26.370  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04691 on 98 degrees of freedom\nMultiple R-squared:  0.8765,\tAdjusted R-squared:  0.8752 \nF-statistic: 695.4 on 1 and 98 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nA model summary output has three parts:\n\n1. Residual statistics (empirical quantiles)\n2. Coefficient statistics\n3. Model statistics\n\nWe already looked at the residuals a lot, so we're starting with the second section here. Each predictor and the intercept has one line in the table, which holds information on both the coefficient estimate and a significance test. A p value smaller than 0.05 indicates that we see a significant partial correlation between that predictor and the response variable. In this case, we have one predictor, the coefficient of which is significantly different from 0. It's also a good idea to look at the confidence interval of coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 0.7156560 1.1754214\npredictor1  0.4700031 0.5465012\n```\n\n\n:::\n:::\n\n\nIn the third section of the summary output, we can see the $R^2$, which ranges from 0 to 1 and gives an indication on much variance of the response variable is explained by the predictor variables. The last line is important, as it tests for significance of the entire model. \n\n### Step 5: Interpret model parameters and reach conclusion\n\nIn this case, a p value of less than 0.05 indicates that the model is significantly different from 0 (no model). We can therefore conclude that the model is significant. Refer to the presentation [here](https://sydney-informatics-hub.github.io/stats-resources/statistical_modelling.html#linear-models-1-linear-regression-anova-ancova-and-repeated-measures-a-simple-mixed-model) for more detail.\n\n### Step 6: Report overall conclusion\n\nTo interpret the paramters, we use the fitted regression coefficient. In our case, using the model table above, we can say (in this case we use \"fake\" predictor and response meanings): \n\n> There is strong evidence to show that predictor1 influences response (p<2e-16), with each 1 unit of increase in predictor1 adding between 0.47-0.54 units of response (95% CI). This effect on weight has been estimated very accurately [as 95% CI is quite narrow].\n\n> The model is a good fit to the data with an $R^2=88\\%$. There were no outliers or unexplained structure. The error was normal.\n\n## Analysis of Variance (ANOVA)\n\nIn this section, we have a `data.frame` object with two variables:\n\n* `treatment`: The treatment variable (binary)\n* `response`: the response variable (metric)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(171975)\nvariance <- rnorm(100, 0, 0.05)\nb0.control <- 3\nb1.treatment <- 0.5\n\ndata1 <- tibble(\n  treatment = factor(c(rep(\"Control\", 50), rep(\"Treatment\", 50))),\n  response = b0.control + b1.treatment*ifelse(treatment==\"Treatment\", 1, 0) + variance\n)\n```\n:::\n\n\nWe assume that the response variable is dependent on the treatment. Due to the binary nature of `treatment`, we are fitting an Analysis of Variance (a subtype of linear model).\n\n### Step 1: Pick suitable model via EDA\n\nFirst, let's visually display both variables using boxplots (as we see in the powerpoint):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(x = treatment, y = response)) +\n  # geom_violin(alpha=0.4, position = position_dodge(width = .75),size=1,color=\"black\") +\n  geom_point(\n    shape = 21,\n    size = 2,\n    position = position_jitter(),\n    color = \"black\",\n    alpha = 1\n  ) +\n  labs(x = \"Treatment\", y = \"Response\") +\n  ggplot(data1, aes(x = treatment, y = response)) +\n  # geom_violin(alpha=0.4, position = position_dodge(width = .75),size=1,color=\"black\") +\n  geom_boxplot(\n    notch = FALSE,\n    outlier.size = -1,\n    color = \"black\",\n    lwd = 1.2,\n    alpha = 0.7\n  ) +\n  labs(x = \"Treatment\", y = \"Response\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nAs we can see above, all observations are clearly separated, indicating a strong treatment effect. \n\nNote: The \"jitter\" creates a nice visual scatter, but is purely for exploration. It should be removed in the final publication.\n\n#### Check for assumptions\n\nFirst, we check for independence using a serial plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = data1, aes(\n  x = seq_along(response),\n  y = response\n)) +\n  geom_point() +\n  labs(x = \"index\", y = \"response values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWe see the separation of treatment values here, but within those there doesn't appear to be any (auto) correlation. Let's check normality next:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Full dataset\") +\n  ggplot(data1, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  facet_wrap(~ treatment) +\n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Divided by treatment\") +\n  plot_layout(ncol = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nWe can see clear separation here as well, otherwise normality. If we only looked in the above plot, we would have assumed non-normality. This is a great example of how we shouldn't worry about violations of normality in the dependent variable too much, since the residuals have to be normally distributed, not the outcome.\n\n#### Outliers\n\nThe combined data (as seen above) exhibits a clear bimodal distribution and deviates significantly from normality. Thus, we need to address whether this poses a problem. However, the error distribution should be normal, not the response, and upon examination, the errors around the mean of each treatment appear to be approximately normal.\n\n### Step 2: Fit model\n\nThere are two ways to fit an ANOVA in R. You can either use the `lm()` function as above, or the `aov()` function. In this case, I'll use the `aov()` function, mainly because I prefer the summary output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_model <- aov(response ~ treatment, data = data1)\n```\n:::\n\n\n### Step 3: Model diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngglm(anova_model, theme = theme_bw()) +\n  ggplot(data = anova_model) +\n  stat_cooks_obs() +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", col = \"red\") +\n  plot_layout(nrow = 2, heights = c(2, 1))\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nThe model diagnostics plot is less informative than with the linear model, due to the binary nature of the `treatment` variable, but we can still observe interesting trends, like with the QQ plot for example.\n\nLet's investigate the residuals a bit more:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(\n  x = residuals(anova_model),\n  y = after_stat(density)\n)) +\n  labs(x = \"Model residuals\") + \n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  ggplot(data1, aes(\n  x = residuals(anova_model),\n  y = after_stat(density)\n)) +\n  geom_density(fill = \"firebrick\") +\n  geom_rug(aes(y = NULL)) +\n  labs(x = \"Model residuals\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThis time, we cannot observe large differences betwen the residuals of the both `treatment` effects, which indicates that the differences are nicely taken into account.\n\n### Step 4: Goodness of Fit\n\nLet's have another look at the Residuals vs Fitted plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(x = treatment, y = residuals(anova_model))) +\n  # geom_violin(alpha=0.4, position = position_dodge(width = .75),size=1,color=\"black\") +\n  geom_boxplot(\n    notch = FALSE,\n    outlier.size = -1,\n    color = \"black\",\n    lwd = 1.2,\n    alpha = 0.7\n  ) +\n  geom_point(\n    shape = 21,\n    size = 2,\n    position = position_jitter(),\n    color = \"black\",\n    alpha = 1\n  ) +\n  labs(x = \"Treatment\", y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThis time we can again see that the residuals are nicely spread around 0 for both treatment and control.\n\nAnother great plot is Fitted vs Residuals as as well as Response vs Residuals :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(\n  x = predict(anova_model), \n  y = residuals(anova_model),\n  col = treatment)) +\n  geom_point() +\n  labs(x = \"Predictions\", y = \"Residuals\") +\n  geom_hline(yintercept = 0, col = \"red\") +\n  theme(legend.position = \"none\") +\n  # Plot 2\n  ggplot(data1, aes(\n  x = response, \n  y = residuals(anova_model),\n  col = treatment)) +\n  geom_point() +\n  labs(x = \"Predictions\", y = \"Residuals\") +\n  geom_hline(yintercept = 0, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nWe expect the ‘lines’ of data rather than a random ‘cloud’ of data which we saw in the regression. This is because rather than a range of predictions for each different value of the predictor we only get 1 prediction for control and another for treatment, hence 2 vertical lines in the upper chart. \n\nLet's also check the response vs. predictions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data1, aes(x = response, y = predict(anova_model))) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, col = \"red\") +\n  labs(y = \"predicted\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nTo check the goodness-of-fit, we have a look at the model summary output:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment    1  6.481   6.481    2400 <2e-16 ***\nResiduals   98  0.265   0.003                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIn this case, we purely observe the significance of our treatment effect, which is seen in the first line of the Anova-Output. A p value of less than 0.05 indicates a significant difference between the categories of the `treatment` variable (of which there are only two).\n\n### Step 5: Interpret Model Parameters and reach a conclusion  \n\nIn order to find out how large the difference is, we need to convert the anova object back to a linear model like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(anova_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       (Intercept) treatmentTreatment \n         3.0017546          0.5091524 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(lm(anova_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       2.5 %    97.5 %\n(Intercept)        2.9871714 3.0163378\ntreatmentTreatment 0.4885287 0.5297761\n```\n\n\n:::\n:::\n\n\nWe can now see that the average difference of `response` between the treatment and control effect is 0.509. Since our effect is significantly different from 0, we can now conclude that our treatment is successful. \n\nRefer to the presentation [here](https://sydney-informatics-hub.github.io/stats-resources/statistical_modelling.html#linear-models-1-linear-regression-anova-ancova-and-repeated-measures-a-simple-mixed-model) for more detail.\n\n### Step 6: Report overall conclusion\n\nYou can use the following sentence (we again assume a \"fake\" meaning):\n\n> There is strong evidence to show that the treatment influences response (p<2e-16). It increases the response by between 0.49-0.53 units (95% CI), from an average of approximately 3 (95% CI=2.98-3.01). This effect on the response has been estimated very accurately [as 95% CI is quite narrow].\n\n> The model is a good fit to the data with an R2=97%. There were no outliers or unexplained structure. The error was normal” \n\n## Analysis of Covariance (ANCOVA)\n\nIn ANCOVA model situations, we are interested in a treatment effect like in ANOVA, but we also want to account for other covariates. This could, for example, be the age of clinical trial candidates.\n\nLet's create some data first (I collapsed this element because it's a lot of code):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(171974)\npredictor.linear1 <- rnorm(100, 6, 0.25)\nvariance <- rnorm(100, 0, 0.05)\n\ntreatment <- factor(c(rep(\"Control\", 50), rep(\"Treatment\", 50)))\n\n# Model 1) if no difference between groups i.e. lines are parrallel\nb0.control <- 1\nb0.treatment <- 0.5\nb1.control <- 1\nb1.treatment <- 0\n\ndata2 <- data.frame()[1:100, ]\ndata2$treatment <- treatment\ndata2$predictor.linear1 <- predictor.linear1\ndata2$response <- b0.control + \n    b1.control*predictor.linear1 + \n    b0.treatment*ifelse(data2$treatment==\"Treatment\", 1, 0) + \n    b1.treatment*ifelse(data2$treatment==\"Treatment\", 1, 0)*predictor.linear1 +\n    variance\nrow.names(data2) <- NULL\n\n\n# Model 2) if  difference between groups i.e. lines aren't parallel\nb0.control <- 1\nb0.treatment <- -8.5\nb1.control <- 1\nb1.treatment <- 1.5\n\ndata3 <- data.frame()[1:100, ]\ndata3$treatment <- treatment\ndata3$predictor.linear1 <- predictor.linear1\ndata3$response <- b0.control + \n    b1.control*predictor.linear1 + \n    b0.treatment*ifelse(data3$treatment==\"Treatment\", 1, 0) + \n    b1.treatment*ifelse(data3$treatment==\"Treatment\", 1, 0)*predictor.linear1 +\n    variance\nrow.names(data3) <- NULL\n```\n:::\n\n\nWe now have three covariates in a `data.frame` object called `data2`, and the same in a different object called `data3`:\n\n* `treatment`: A categorical variable depicting the treatment/control groups\n* `predictor.linear1`: Our numeric predictor\n* `response`: The numeric response\n\nLet's look at our datasets graphically:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd2graph <- ggplot(data2, aes(x = predictor.linear1, y = response, col = treatment)) +\n  geom_point() +\n  guides(col = \"none\") +\n  labs(x = \"predictor.linear1 values\", title = \"Scatterplot data2\")\nd3graph <- ggplot(data3, aes(x = predictor.linear1, y = response, col = treatment)) +\n  geom_point() +\n  labs(x = \"predictor.linear1 values\", title = \"Scatterplot data3\")\nd2graph + d3graph\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nWe can now see the relationship between `predictor.linear1` and `response` in two different scenarios (`data2` vs `data3`). The difference is that on the left graph, the differently coloured points have a parallel increase, whereas on the right graph the slopes of the increase between the points is also different. We will be further using `data3`, because it has a more complex (and interesting) model structure.\n\n### Step 1: Pick suitable model using EDA\n\nFrom the (right) graph above, we can see that there is a binary treatment effect as well as a linear predictor called `predictor.linear1`. This is a classic ANCOVA scenario. \n\n#### Model assumptions\n\nFirst, let's check whether the response observations seem to be (auto) correlated using a serial plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = data3, aes(\n  x = seq_along(response),\n  y = response,\n  col = treatment\n)) +\n  geom_point() +\n  labs(x = \"index\", y = \"response values\") +\n  ggplot(data = data3, aes(\n  x = seq_along(response),\n  y = predictor.linear1,\n  col = treatment\n)) +\n  geom_point() +\n  labs(x = \"index\", y = \"predictor.linear1 values\") +\n  plot_layout(guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nNo pattern visible, except the one created by the treatment effect, which we will later account for in the model. Next, we check for normality and look for apparent outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data3, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Full dataset\") +\n  ggplot(data3, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  facet_wrap(~ treatment) +\n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Divided by treatment\") +\n  plot_layout(ncol = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nWe can see that there are visible differences in the response variable broken up by the treatment effect, but this is not concerning, both histograms still appear mostly normal, just with differences in the variance and location of the distribution. This is a great example of how we shouldn't worry about violations of normality in the dependent variable too much, since the residuals have to be normally distributed, not the outcome.\n\n### Step 2: Fit model\n\nLet's fit the model next. Due to the different slopes in the predictor variable in different treatment effects, it is required that we fit an interaction between `treatment` and `predictor.linear1`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nancova_model <- aov(\n  response ~ treatment + predictor.linear1 +\n  treatment * predictor.linear1,\n  data = data3\n)\n```\n:::\n\n\n### Step 3: Model diagnostics\n\nOur classic five diagnostic plots can be created first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngglm(ancova_model, theme = theme_bw()) +\n  ggplot(data = ancova_model) +\n  stat_cooks_obs() +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", col = \"red\") +\n  plot_layout(nrow = 2, heights = c(2, 1))\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nAll of these plots look very well behaved. We can't detect any visible pattern in the plots, neither can we find any observations that are too influental.\n\nNext, let's have a look at the residuals, and whether there is still a visible pattern:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data3, aes(\n  x = residuals(ancova_model),\n  y = after_stat(density)\n)) +\n  labs(x = \"Model residuals\") + \n  geom_histogram(col = \"black\", fill = \"cornflowerblue\") +\n  ggplot(data3, aes(\n  x = residuals(ancova_model),\n  y = after_stat(density)\n)) +\n  geom_density(fill = \"firebrick\") +\n  geom_rug(aes(y = NULL)) +\n  labs(x = \"Model residuals\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe residuals look very nicely behaved, no non-normality can be detected.\n\n### Step 4: Goodness-of-fit\n\nLet's have another look at the Residuals vs Fitted plot, as well as Residuals vs response:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data3, aes(\n  x = predict(ancova_model), \n  y = residuals(ancova_model), \n  col = treatment)) +\n  geom_point() +\n  geom_smooth(se = FALSE, method = \"lm\") +\n  labs(x = \"Predictions\", y = \"Fitted values\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  ggplot(data3, aes(\n  x = predictor.linear1, \n  y = residuals(ancova_model), \n  col = treatment)) +\n  geom_point() +\n  geom_smooth(se = FALSE, method = \"lm\") +\n  labs(x = \"predictor.linear1 values\", y = \"Fitted values\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-36-2.png){width=672}\n:::\n:::\n\n\nEven separated by the treatment effect, no pattern is apparent. Had we forgotten to fit an interaction effect, we would still see some remaining slopes or strange deviations from the line.\n\nLet's dig deeper into the residuals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data3, aes(x = predict(ancova_model), y = residuals(ancova_model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\") +\n  labs(x = \"predicted values\", y = \"residuals\") +\n  ggplot(data3, aes(x = response, y = residuals(ancova_model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\") +\n  labs(x = \"predicted values\", y = \"residuals\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nNo evidence of outliers, or unexplained structure or non linearity.\n\nWe can also compare the predictions vs. the response:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data3, aes(x = response, y = predict(ancova_model))) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, col = \"red\") +\n  labs(x = \"response\", y = \"model predictions\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nLet's check the summary output next:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ancova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment                    1  9.809   9.809    4412 <2e-16 ***\npredictor.linear1            1 19.388  19.388    8721 <2e-16 ***\ntreatment:predictor.linear1  1  3.125   3.125    1406 <2e-16 ***\nResiduals                   96  0.213   0.002                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAs we can see, all three fitted effects are significantly different from zero, indicating a successful treatment effect. \n\n### Step 5: Interpret Model Parameters and reach a conclusion  \n\nIf we want to know how large our coefficiencts are, we need to convert the model back to a \"linear model\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(ancova_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         (Intercept)                   treatmentTreatment \n                           0.8589649                           -8.3203390 \n                   predictor.linear1 treatmentTreatment:predictor.linear1 \n                           1.0222017                            1.4711692 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(lm(ancova_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                          2.5 %    97.5 %\n(Intercept)                           0.5150596  1.202870\ntreatmentTreatment                   -8.7882616 -7.852416\npredictor.linear1                     0.9646711  1.079732\ntreatmentTreatment:predictor.linear1  1.3932757  1.549063\n```\n\n\n:::\n:::\n\n\nThe treatment effect seems to be negative in this case, but it can only be interpreted jointly with the interaction. As such, while the treatment effect by itself is negative, the slope of it's interaction with predictor.linear1 is positive, so the values do rise above the control group quite quickly. This becomes apparent in the scatterplot shown in the first part of this section (EDA).\n\nThis does indicate that the treatment effect strongly interacts with the `predictor.linear1` variable.\n\nRefer to the presentation [here](https://sydney-informatics-hub.github.io/stats-resources/statistical_modelling.html#linear-models-1-linear-regression-anova-ancova-and-repeated-measures-a-simple-mixed-model) for more detail.\n\n### Step 6: Report overall conclusion\n\nYou can again use the following sentences (assuming a fake application):\n\n> There is strong evidence to show that predictor.linear1 impacts the response (p<2e-16), with each unit of predictor.linear1 adding between 0.96-1.08 units of response (95% CI). \n\n> There is strong evidence that the treatment have a positive effect on the impact of predictor.linear1 (p<2e-16), increasing its effect by between 1.39-1.55 (95% CI), for a total average effect of 2.5 units of response increase for each unit increase of predictor.linear1.\n\n> This effect of predictor.linear1 on response has been estimated very accurately [as 95% CI is quite narrow].\n\n> The model is a good fit to the data with an R2=99%. There were no outliers or unexplained structure. The error was normal\n\n\n## Linear Mixed Models\n\nWe use Mixed Models when we cannot assume that all observations are independently distributed, due to an error term structure that we need to take into account. This could be due to repeated measures where we take a measurement multiple times for each unit of observation (and therefore each unit's measurements are correlated) or a \"nested structure\", like students in a classroom.\n\nLet's create some data first to illustrate the example:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(171974)\nvariance <- rnorm(100, 0, 250) # as within person variance is 100 \n\nid <- rep(c(1:10), 2, each=5)\ntreatment <- factor(c(rep(\"Control\", 50), rep(\"Treatment\", 50)))\n\nb0.control.average <- 4000\nb0.control.0 <- rnorm(10, b0.control.average, 1500) # as range 1000-9000\nb0.control <- rep(b0.control.0, 2, each=5)\nb1.treatment <- 500\n\ndata6 <- data.frame()[1:100, ]\ndata6$id <- as.factor(id)\ndata6$treatment <- treatment\ndata6$response <- b0.control + b1.treatment*ifelse(data6$treatment==\"Treatment\", 1, 0) + variance\ndata6 <- data6[order(data6$id, data6$treatment),]\nrow.names(data6) <- NULL\ndata6$b0.control <- b0.control\n\nwritexl::write_xlsx(x = data6, path = \"lm1_dataset_linear_mixed_models.xlsx\")\n```\n:::\n\n\nIn our new `data.frame`, we now have a new variable `id`, which specifies the unit of observation. This is \"repeated\", as we take each unit of observation multiple times. Our variables are thus:\n\n* `id`: ID of the unit of observation\n* `b0.control`: This is our numeric predictor variable, which is unique for each unit of observation but not for each repeated measure.\n* `treatment`: This contains information about the treatment/control groups\n* `response`: Our target variable\n\n### Step 1: Pick a suitable model to fit to the data via EDA\n\nLet's first graphically display the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(\n  x = id,\n  y = response,\n  col = treatment\n  )) +\n  geom_point() +\n  labs(x = \"id\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nIn this graph, we can both see a horizontal trend between `b0.control` and `response` as well as the multiple repetitions scattered vertically. This is a perfect mixed model scenario. We can see that the observations are correlated within the `id` variable.\n\n#### Check assumptions\n\nThe first assumption we'll check is the we already know will be broken: independence. A serial plot helps to see this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = data6, aes(\n  x = seq_along(response),\n  y = response\n)) +\n  geom_point() +\n  labs(x = \"index values\", y = \"response values\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nWe can definitely see the repetition pattern here. Let's check normality next:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Full dataset\") +\n  ggplot(data6, aes(\n  x = response,\n  y = after_stat(density)\n)) + \n  facet_wrap(~ treatment) +\n  geom_histogram(fill = \"cornflowerblue\", col = \"black\") +\n  geom_density(aes(fill = NULL)) +\n  labs(title = \"Divided by treatment\") +\n  plot_layout(ncol = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nWe see a slight right-skew in both treatment and control response groups. This is nothing to worry about yet, however, since the residuals need to be normally distributed, not the response. This is a great example of how we shouldn't worry about violations of normality in the dependent variable too much, since the residuals have to be normally distributed, not the outcome.\n\n### Step 2: Fit the Model\n\nNow, we fit our mixed model. In general, mixed models have a slightly different notation as linear \"unmixed\" models, since we have to distinguish between \"fixed\" (uncorrelated) and \"random\" (correlated) effects. The variable which \"nests\" the observation is our random effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmixed_model <- lmer(response ~ treatment + (1 | id), data = data6)\n```\n:::\n\n\n### Step 3: Model diagnostics\n\nLet's do our classic 5-graph model diagnostics first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngglm(mixed_model, theme = theme_bw()) +\n  ggplot(data = mixed_model) +\n  stat_cooks_obs() +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", col = \"red\") +\n  plot_layout(nrow = 2, heights = c(2, 1))\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nOur graphs look pretty good. There are no influental observations that we can see.\n\nLet's have a closer look at the residuals, to see whether there is any pattern left:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(\n  x = residuals(mixed_model),\n  y = after_stat(density)\n)) +\n  labs(x = \"Model residuals\") +\n  geom_histogram(col = \"black\", fill = \"cornflowerblue\") +\n  ggplot(data6, aes(\n  x = residuals(mixed_model),\n  y = after_stat(density)\n)) +\n  geom_density(fill = \"firebrick\") +\n  geom_rug(aes(y = NULL)) +\n  labs(x = \"Model residuals\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nThe residuals seem to be greatly behaved, and pretty normal now (especially in comparison to the response graph from before). \n\n### Step 4: Goodness of fit\n\n#### Outliers and unexpected structure or nonlinearity\n\nLet's have another look at the residuals vs fitted plot as well as response vs residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(\n  x = predict(mixed_model), \n  y = residuals(mixed_model), \n  col = treatment)) +\n  geom_point() +\n  geom_smooth(se = FALSE, method = \"lm\") +\n  labs(x = \"predictions\", y = \"Fitted values\") +\n  theme(legend.position = \"none\") +\n  ggplot(data6, aes(\n  x = response, \n  y = residuals(mixed_model), \n  col = treatment)) +\n  geom_point() +\n  labs(x = \"response values\", y = \"Fitted values\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThere is some remaining structure in the control and treatment slopes, however this is likely due to this graph not having accounted for the individual repetitions.\n\nAs we can see in the plot above, there is no evidence of outliers, unexplained structure or non linearity. Notice the predicted scores are falling out into 20 discrete vertical patterns of 5 points. This is expected since we had 5 repeated measures for 10 patients over 2 treatments.\n\nLet's also have a look at the response vs predicted graph:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(x = response, y = predict(mixed_model)), col = id) +\n  geom_point() +\n  labs(y = \"predicted values\") +\n  geom_smooth(method = \"lm\", se = FALSE, col = \"red\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nWe should also check response vs residuals as well as predict vs. residuals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data6, aes(x = predict(mixed_model), y = residuals(mixed_model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\") +\n  labs(y = \"residuals\", x = \"predicted\") +\n  ggplot(data6, aes(x = response, y = residuals(mixed_model))) +\n  geom_point() +\n  geom_hline(yintercept = 0, col = \"red\") +\n  labs(y = \"residuals\") +\n  plot_layout(guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](linear_modelsI_workflow_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nAfter assessing the model diagnostics, let's look at the summary output.\n\n### Step 5: Model interpretation and conclusion\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: response ~ treatment + (1 | id)\n   Data: data6\n\nREML criterion at convergence: 1415.9\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.00798 -0.64360 -0.01528  0.64054  2.39706 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n id       (Intercept) 2178377  1475.9  \n Residual               59105   243.1  \nNumber of obs: 100, groups:  id, 10\n\nFixed effects:\n                   Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)        3398.202    467.996    9.049   7.261 4.63e-05 ***\ntreatmentTreatment  563.738     48.623   89.000  11.594  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\ntrtmntTrtmn -0.052\n```\n\n\n:::\n:::\n\n\nAs we can see from the above output, we have a significant treatment effect. The control variable `b0.control`, though, is not significantly different from 0. \n\nRefer to the presentation [here](https://sydney-informatics-hub.github.io/stats-resources/statistical_modelling.html#linear-models-1-linear-regression-anova-ancova-and-repeated-measures-a-simple-mixed-model) for more detail.\n\n### Step 6: Report overall conclusion\n\nWith the model output above, we can now make a conclusion. In order to do so, let's first also calculate the confidence intervals of each estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(mixed_model)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nComputing profile confidence intervals ...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       2.5 %    97.5 %\n.sig01              953.2940 2340.1219\n.sigma              210.3224  281.8879\n(Intercept)        2437.6856 4358.7182\ntreatmentTreatment  467.9490  659.5266\n```\n\n\n:::\n:::\n\n\nThe following statement can now be made:\n\n> There is strong evidence to show that the treatment influences the response (p<2e-16). It increases # of the response by 0.32 to 0.45 (95% CI). This effect has been estimated fairly accurately [as 95% CI isn’t too wide]. \n\n#### Was it worth fitting the more complex model?\n\nLet's compare the random (output above) to the fixed model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixed_effects_anova <- lm(response ~ treatment, data = data6)\nsummary(fixed_effects_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = response ~ treatment, data = data6)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3302.0  -939.6   373.6  1040.5  2138.0 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          3398.2      203.0  16.743   <2e-16 ***\ntreatmentTreatment    563.7      287.0   1.964   0.0524 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1435 on 98 degrees of freedom\nMultiple R-squared:  0.03787,\tAdjusted R-squared:  0.02805 \nF-statistic: 3.857 on 1 and 98 DF,  p-value: 0.05236\n```\n\n\n:::\n:::\n\n\nIf we fit a simple ANOVA model like we did previously it shows marginal support that the treatment has an impact (treatment p=0.0524) while the random model has strong support (p < 2e-16). This is because the effect of treatment has been hidden by the noise in the data set (residual=1435), while the residual for the random model is much smaller (222) meaning it has more power. This is because the differences between subjects is included in the fixed effects residual, but is partitioned out in the random effects as the id-intercept SD (1580). \n\n\n> There was much larger variation between patients (sd=1.0151) than within (sd=0.1678), meaning it was worthwhile partitioning it out for a more accurate model.\n",
    "supporting": [
      "linear_modelsI_workflow_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}